title: POP BEAT FINLAND
description: Tuotteiden esittely
theme: jekyll-theme-tactile # Voit vaihtaa teeman
show_downloads: true
baseurl: "" # Jos projekti ei ole suoraan juurikansiossa, lis채채 sen nimi t채h채n
url: "https://erkkipuumalainen.github.io"
